title: Ch0i Changhee
url: "https://cyberhamster500.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
#footer_url: "https://ch0ich.github.io"
footer_text: "© 2025 Ch0i Changhee. All rights reserved."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"  
 - name: "Publication"
   link: "publication"
 - name: "Contact"
   link: "contact"
